export const SITE = {
  name: 'Neural Computation Laboratory',
  shortName: 'NCL',
  description: 'We investigate how neural circuits represent, transform, and communicate information using computational, theoretical, and experimental approaches.',
  url: 'https://compneuro-lab.university.edu',
  institution: 'University of Somewhere',
  department: 'Department of Neuroscience',
  address: '42 Campus Boulevard, 75005 Paris, France',
  email: 'lab@university.edu',
  twitter: '@neurocomplab',
  github: 'https://github.com/evasquez-lab',
  pi: 'Elena Vasquez',
  piSlug: 'vasquez',
  founded: 2018,
  logo: '/images/lab-logo.svg',
  ogImage: '/images/og-default.png',
  nav: [
    { label: 'About', href: '/about' },
    { label: 'Research', href: '/research' },
    { label: 'Publications', href: '/publications' },
    { label: 'Team', href: '/team' },
    { label: 'Projects', href: '/projects' },
    { label: 'News', href: '/news' },
    { label: 'Teaching', href: '/teaching' },
    { label: 'Resources', href: '/resources' },
    { label: 'Contact', href: '/contact' },
  ],
} as const;
