export const SITE = {
  name: 'DeLi Lab — Development of Literacy Laboratory',
  shortName: 'DeLi Lab',
  description: 'We study the acquisition and disorders of written language — reading, spelling, and handwriting — to better understand and support children in educational and clinical settings.',
  url: 'https://www.delilabucl.com',
  institution: 'Université catholique de Louvain',
  department: 'Institut de Recherche en Sciences Psychologiques (IPSY)',
  address: 'Place Cardinal Mercier 10, 1348 Louvain-la-Neuve, Belgium',
  email: 'delilab.ucl@gmail.com',
  twitter: '@delilabucl',
  github: 'https://github.com/delilabucl',
  pi: 'Marie Van Reybroeck',
  piSlug: 'van-reybroeck',
  founded: 2009,
  logo: '/images/lab-logo.svg',
  ogImage: '/images/og-default.png',
  nav: [
    { label: 'Research',       href: '/research' },
    { label: 'Team',           href: '/team' },
    { label: 'Publications',   href: '/publications' },
    { label: 'Projects',       href: '/projects' },
    { label: 'Resources',      href: '/resources' },
    { label: 'Contact',        href: '/contact' },
  ],
} as const;
